### ISSUE TITLE
User can sign up

### ISSUE THREAD

**Issue by anthony-urbina** [AnthonyUrbina/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign up

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to log in. If they do not already have an account, they will be able to create one.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-11-07 at 11 36 24 AM](https://user-images.githubusercontent.com/109625982/200399318-434c37cd-6379-4de5-bdee-9f9e608c95e2.png)
![Screen Shot 2022-11-07 at 11 46 22 AM](https://user-images.githubusercontent.com/109625982/200403034-a9f61d31-5938-46e0-bb2d-874842d112ab.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to include code for my custom schema
- [x] Update `data.sql` to include code for inserting any necessary dummy data
- [x] Start postgreSQL in my command line
- [x] Create my database
- [x] Execute schema.sql
- [x] Execute data.sql
- [x] Start up pgweb if necessary

### ☁️ Server Tasks

- [x] Update `server/index.js` to ...
  - [x] require `dotenv/config`
  - [x] require pg from the `pg` package
  - [x] require express from the `express` package
  - [x] require argon2 from the `argon2` package
  - [x] require ClientError from `./client-error`
  - [x] require errorMiddleware from `./error-middleware`
  - [x] create a new instance of pg.Pool and assign it to a variable
  - [x] create an app object
  - [x] call express.json() and mount it's return using app.use()
  - [x] User can sign up
    - [x] listen for a post request at 'api/auth/sign-up'
      - [x] check if a username and password were entered
        - [x] if not, throw a ClientError, status 400, 'username and password are required fields'
      - [x] hash the users password with argon 2
        - [x] then insert the username and hashed password into the "users" table
        - [x] then send a response to the client, status 201, and show them the "userId" and "username" columns for that 
                user.
      - [x] catch any errors
  - [x] Listen on port specified in .env
  - [x] Mount the errorMiddleware using app.use()
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to reflect the state of the App
- [x] state should store route: 'sign-up'
- [x] componentDidMount should store an event listener for 'hashchange'
  - [x] it should set state to the value of the new hash 
- [x] User can sign up
  - [x] create a sign up view
    - [x] it should have a controlled form
    - [x] username and password value's should be stored in the state
    - [x] onChange listeners should be applied to the input elements, w a callback attached to update state
    - [x] value props should be applied to the input elements, pointing to state for their values
    - [x] onSubmit listener should be placed on the from element, w a callback
      - [x] the call back should send a fetch request to 'api/auth/sign-up'
      - [x] then, parse the string body that was returned
      - [x] then, check if the action was a 'sign-up'
        - [x] if true, set hash to 'sign-in'

### 🧑‍⚕️ Clean Up Tasks

 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
