### ISSUE TITLE
User can face-off

### ISSUE THREAD

**Issue by anthony-urbina** [AnthonyUrbina/final-project#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can face-off.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When both users have placed their cards, the user with the highest scoring card will keep the two cards that are currently on the table. Both cards will be placed, face-up, in a new card pile to the left of their main deck.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Screen Shot 2022-11-07 at 2 01 19 PM](https://user-images.githubusercontent.com/109625982/200428749-8525c199-32d0-4551-b8e4-7e53a095189f.png)
![Screen Shot 2022-11-07 at 2 01 28 PM](https://user-images.githubusercontent.com/109625982/200428753-e886d292-684e-4e99-9b1b-353b8fa3f025.png)
![Screen Shot 2022-11-07 at 2 03 06 PM](https://user-images.githubusercontent.com/109625982/200428783-699e3239-2525-4804-bcf9-4d6d366faa8b.png)
![Screen Shot 2022-11-07 at 2 03 18 PM](https://user-images.githubusercontent.com/109625982/200428785-f62b9ef9-179d-4f71-883c-153ba245476c.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [ ] Update `server/index.js` to
- [x] in patch request to '/api/games/:gameId
  - [x] check the result of the db.query
  - [x] if battlefieldEmpty is false
  - [x] call decideWinner()
  - [x] pass it both card values and names of both players
- [x] create a decideWinner() function
    - [x] it should evaluate the two cards
    - [x] if it's a tie
      - [x] pick a random number (1-10)
      - [x] if number is greater than 5 return player1Username
      - [x] if number is less than 5 return player2Username
    - [x] else, return the winner
### ⚡ Client Tasks

- [ ] Update component to ...
- [x] update flipCard() method
  - [x] if both players CardShowing properties are not null
    - [x] add battlefieldEmpty property to state and set it to false 
- [x] create a checkBattlefield() method
  - [x] it should call decideWinner() with a .75s delay if there are two cards in play
- [x] create a showClientWinningCards() method
  - [x]  as long as client's sideDeck is not empty
    - [x] select the last two cards in the array
    - [x] create img tags for them and return them
- [x] create a showOpponentWinningCards() method
  - [x]  as long as opponent's sideDeck is not empty
    - [x] select the last two cards in the array
    - [x] create img tags for them and return them
- [x] on componentDidMount()
  - [x] socket.on('winner-decided', results)
    - [x] use setState() to move both cards that were in the battlefield into the winners sideDeck array
### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
