### ISSUE TITLE
User can win a match

### ISSUE THREAD

**Issue by anthony-urbina** [AnthonyUrbina/final-project#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can win a match.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The objective of the game is to take ALL of your opponents cards. So once a user obtains all cards on the field, that user will be deemed as the winner of that match. A congratulatory modal will appear on both user's screens. The modal will have a "Main Menu" button which will redirect the user to that home page once they click it. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="702" alt="Screen Shot 2022-12-04 at 2 23 10 PM" src="https://user-images.githubusercontent.com/109625982/205519006-1c92478d-b136-4a5a-9fda-6d2d61a23776.png">
<img width="227" alt="Screen Shot 2022-12-04 at 2 25 02 PM" src="https://user-images.githubusercontent.com/109625982/205519008-480397ed-995e-48f0-b0f1-aab7fb0fcf72.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `data.sql` to ...
  - [x] add isActive column to games column
  - [x] boolean value 

### ☁️ Server Tasks

- [x] Update `server/index.js` ...
- [x] update path at '/api/games/:gameId
  - [x] when db query results are received 
    - [x] if a player's deck is empty but their sideDeck is not or
    - [x] if a players deck and and sideDeck are both empty
      - [x] call outOfCards(state)
- [x] create an outOfCards(state) method
  - [x] if a player's deck is empty but their sideDeck is not
    - [x] move sideDeck cards into main deck
    - [x] make sure sideDeck is empty
    - [x] update state
    - [x] update games table with updated state
    - [x] then,
      - [x] io.to(roomId).emit('deck-replaced', state)
  - [x] if a players deck and and sideDeck are both empty
    - [x] it should declare that player's opponent the winner
    - [x] add winner property to state
    - [x] update the database: state column => new state and isActive column => false
      - [x] then, it should io.to(roomId).emit('game-over',  state)

### ⚡ Client Tasks

- [x] Update component ...
- [x] create showWinnerModal() method
  - [x] destructure loser property from state
  - [x] destructure client username from props
  - [x] if loser is truthy
    - [x] if winner is equal to client, show bald avatar and 'You'
    - [x] else,  show blonde avatar and 'opponentUsername'
- [x] create showOpponentDeck() method
  - [x] destructure loser from state
  - [x] get opponent's username
  - [x] if opponentDeck is empty
    - [x] return nothing
  - [x] otherwise return the deck 
- [x] create showClientDeck() method
  - [x] destructure loser from state
  - [x] destructure client username from props
  - [x] if clientsDeck is empty
    - [x] return nothing
  - [x] otherwise return the deck 

### 🧑‍⚕️ Clean Up Tasks

 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
