### ISSUE TITLE
User can sign in 

### ISSUE THREAD

**Issue by anthony-urbina** [AnthonyUrbina/final-project#12]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-11-07 at 11 55 40 AM](https://user-images.githubusercontent.com/109625982/200402784-8fc65de4-6b89-49e2-9987-4aec2330dcbc.png)
![Screen Shot 2022-11-07 at 11 46 15 AM](https://user-images.githubusercontent.com/109625982/200400824-b099f20a-a2e3-4ddd-89ff-2a5993154f55.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to ...
- [x] Update `data.sql` to ...

### ☁️ Server Tasks

- [x] Update `server/index.js` to ...
- [x] User can sign in 
    - [x] listen for a post request at 'api/auth/sign-in'
      - [x] check if a username and password were entered
        - [x] if not, throw a ClientError, status 400, 'username and password are required fields'
      - [x] query the database for the "userId" and "hashedPassword" for the "username" that was entered
        - [x] then
         - [x] if no user is found, throw a ClientError, status, 401, "invalid login"
         - [x] else, create a payload object with "username" and "userId" properties
         - [x] use argon2.verify() to verify that the salt of hashedPassword + password yield the correct hashed password
           - [x] then, if they don't, throw a new ClientError, 401 "invalid login" , else
             - [x] create a new token with jwt.sign(). Payload and token secret as arguments.
             - [x] send a response to the client, status 200, show them the payload and token in the response
             - [x] catch any errors
       - [x] catch any errors
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to ...
- [x] User can sign in
  - [x] create a handleSignIn function in App component
    - [x] store the users token in local storage
    - [x] call setState() to update user and token
    - [x] add it to context and pass to AuthPage, then pass as prop to AuthForm
  - [x] state of App should include a route property that displays the current windows hash
    - [x] it should also include a user property
    - [x] create context with these values and pass them to AuthPage, then pass as props to AuthForm
    - [x] use these values to: 
    - [x] change the text/href of the <a> element
    - [x] change the text of the sign in/sign up button
    - [x] determine the post route to send the send the post request to
    - [x] determine the hash route once the sign in/sign up button is pressed
  - [x] it should also have a componentDidMount that listens for hashchanges and updates state to the latest hash
  - [x] Make sure sign-in form maintains the same functionality as sign up form
    - [x] it should have a controlled form
    - [x] username and password value's should be stored in the state
    - [x] onChange listeners should be applied to the input elements, w a callback attached to update state
    - [x] value props should be applied to the input elements, pointing to state for their values
    - [x] onSubmit listener should be placed on the from element, w a callback
      - [x] the call back should send a fetch request to 'api/auth/sign-in'
      - [x] then, if a user and token are found in the response
      - [x] call handleSignIn
      - [x] set hash to ''
- when the sign in button is pressed, user should be redirected to a blank page
### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
