### ISSUE TITLE
User can sign out

### ISSUE THREAD

**Issue by anthony-urbina** [AnthonyUrbina/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign out

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will click on the sign out button (top right of page). They will then be shown a modal, warning them that they will exit their current lobby if they log out. The user will then be able to confirm or cancel the status of their log out.  

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-11-07 at 11 41 11 AM](https://user-images.githubusercontent.com/109625982/200401519-eaab11f2-6eb6-4416-93d2-681cc63f18c9.png)
![Screen Shot 2022-11-07 at 11 52 07 AM](https://user-images.githubusercontent.com/109625982/200401812-b9f4bf8c-cab1-4435-a2a4-336355ef9e4b.png)
![Screen Shot 2022-11-07 at 11 44 09 AM](https://user-images.githubusercontent.com/109625982/200401660-ca64083d-75d7-437a-8a49-a38f29fbc6e8.png)
![Screen Shot 2022-11-07 at 11 44 33 AM](https://user-images.githubusercontent.com/109625982/200401662-5660d3f4-df4a-4ef0-b601-d0102e221991.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Update component to ...
- [x] add signOutModalShowing property to state
- [x] add returnHomeModalShowing property to state
- [x] create a handleSignOut() method
  - [x] it should clear local storage
  - [x] it should change hash to '""
- [x] import sign out button from font awesome
- [x] place it on top right of lobby and competition room components
- [x] import return home button from font awesome
- [x] place it on top left of lobby component
- [x] create sign out confirmation modal
- [x] create return home confirmation modal
- [x] when sign-out button is clicked
  - [x] update state.  set signOutModalShowing to true
- [x] when cancel-button is clicked
  - [x] hide all modals  
- [x] create handleClick() method
  - [x] when sign-out button is clicked
    - [x] update state.  set signOutModalShowing to true
  - [x] when cancel-button is clicked
    - [x] hide all modals
  - [x] when home button is clicked
  - [x] update state.  set returnHomeModalShowing to true
 
### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
