### ISSUE TITLE
User can battle

### ISSUE THREAD

**Issue by anthony-urbina** [AnthonyUrbina/final-project#21]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can battle.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
When both users put down a card with the same rank, instead of appointing a random winner, both users will place an additional 3 cards on the table.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-12-15 at 11 56 13 AM](https://user-images.githubusercontent.com/109625982/207956727-23084471-48d6-45e3-ba56-6bd62daa4aed.png)
![Screen Shot 2022-12-15 at 11 57 49 AM](https://user-images.githubusercontent.com/109625982/207956732-49a1f0d6-778b-4f15-adff-add092956c9b.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to ...
- [x] update handleFaceoffWin, rename to handleWin()
- [x] whether its a battle or not
- [x] it should take all cards that are faceUp and push them to the winnings pile
- [x] and if there are any cards in the battlePile, it should push those to winnings also

### ⚡ Client Tasks

- [x] Create a component to ...
- [x] Update component to ...
- [x] when the backend detects a tie
- [x] it should declare a tie, not pick a random winner
- [x] when it calls handleFaceoffWin, winner wil be null
- [x] so instead of calling it, create conditional logic that says
- [x] if there is a winner, call handleFaceoffWin, else call handleFaceoffTie
- [x] therefore, i need to create handleFaceoffTie
- [x] what will be the responsibilities, of handleFaceoffTie? what information does it need to fulfill these responsibilities
- [x] it will need a state to make changes to
- [x] it's responsibility is to communicate to the client that it is now in a battle
- [x] it should update the db to reflect this new state
- [x] client will receive the message that it is now in a battle, state change effective immediatley
- [x] right now, flipCard() only flips card after checking to see that either player doesn't already have a card on the table
- [x] so we need to add a condition, that overrides the previous if users are in a battle
- [x] this will allow them to flip more cards
- [x] but how do we limit the cards we want them to be able to place, remember, they should only be able to click 4 times
- [x] take into consideration, that this battle could end up in a tie, where players would need to place down 4 more cards
- [x] to deal with this, i propose that battles cary stages, rather than booleans.
- [x] if a battle is stage 1 then users will be given 4 additional clicks
- [x] if a battle is stage 2 then users will be given 4 more clicks, so on so fourth
- [x] so that handles the clicks, but how will the cards actually be placed?
- [x] perhaps a method like showPlayerBattleCards()?
- [x] if there are cards in the battle pile show them, starting from the first
- [x] move rn is to create static properties up to 9 (12 maybe or figure out how to do this dynamically) and have class be applied to the cards conditionally
- [x] battlePile is not empty
- [x] map through and return a face-up card for each element
- [x ] this is good
- [x] back to flipCard() logic
- [x] i mentioned a battlePile array for both players above, but havent laid out a plan
- [x] there will be a battlePile, that is where your first 3 cards will go
- [x] semantically, it would make sense for the fourth card to go into the players CardFlipped array rather than battlePile
- [x] it may also make sense to create a new property for BattleCardFlipped
- [x] i think going w CardFlipped makes sense because i can return all the cards together
- [x] all battle cards that get flipped need to appear higher in the deck than cards from previous stages
- [x] so here, we will repeat logic for the carflipped() method except that battle cards will start w higher indexes than cards before them
- [x] once all 4 cards have been placed, make sure that this information has been recieved by the server
- [x] the user should be able to refresh and still come back to whatever the game state was before the refresh
 ### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
