### ISSUE TITLE
User can view a list of online users

### ISSUE THREAD

**Issue by anthony-urbina** [AnthonyUrbina/final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a list of online users

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

There will be an "Online Players" button on the app's home page. The user will click this button and a modal will appear. The modal will show a list of players who are currently online.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-11-07 at 11 41 11 AM](https://user-images.githubusercontent.com/109625982/200405751-849625be-208e-4348-bd70-7d20753edd61.png)
![Screen Shot 2022-11-07 at 11 41 33 AM](https://user-images.githubusercontent.com/109625982/200405757-14bdc27b-18b0-45d8-91e1-29cce53177e2.png)
![Screen Shot 2022-11-07 at 11 44 33 AM](https://user-images.githubusercontent.com/109625982/200405797-c580ebc4-f34b-45c9-bd61-92df6dc8e945.png)
![Screen Shot 2022-11-07 at 11 44 42 AM](https://user-images.githubusercontent.com/109625982/200405800-0f36b428-5fed-4392-bff0-b6dd396b6101.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

everytime a user creates an account, i will link a png to their user object
- [x] Update `server/index.js` to ...
- [x] require http from the http module
- [x] create an http server with http.createServer(app)
- [x] import Server class from socket.io 
- [x] create a new socket io server
- [x] change app.listen to server.listen
- [x] create a clientList object 
- [x] listen for a 'connection' event
  - [x] get payload of the connected user
  - [x] deconstruct username from the payload
  - [x] pair the username and socket id of connected client
  - [x] push the paired info to the clientList object
  - [x] emit the updated clientList object to all sockets/clients
- [x] listen for a 'disconnect event'
  - [x] delete the disconnected socket.id property and it's value from the clientList object
  - [x] send the client the socket.id of the disconnected user
 

### ⚡ Client Tasks
client is going to need to ask server for a list of clients each time

- [x] import io from 'socket.io-client'
- [x] create a Lobby component that matched the lobby designed in figma
- [x] on componentDidMount
  - [x] check if a user is logged in
    - [x] if they are, then create a new socket
    - [x] pass auth as the second parameter
    - [x] it's value should be the signed in user's payload
  - [x] on socket.on('onlinePlayers')
    - [x]  delete the current socket.id from the clientList that was received from the server
    - [x] use setState() to update onlinePlayers
  - [x] on socket.on('user disconnected')
    - [x] create a copy of this.state.onlinePlayers
    - [x] delete the disconnect socket.id property and it's value from the copy of the onlinePlayers object
    - [x] use setState() to update onlinePlayers
 - [x] on componentWillUnmount
   - [x]  if there is a live socket connection
     - [x] terminate it
 - [x] create a showActivePlayers method
   - [x] it should loop through all this.state.onlinePlayers
   - [x] push all usernames into an array
   - [x] map through the array
   - [x] bundle the players username with an image
   - [x] return the bundle
 - [x] create a handleClick method
   - [x] anytime the user clicks the 'Online Players' button, this.state.modalIsActive should be true
   - [x] anytime the user clicks the 'X' button within the modal, this.state.modalIsActive should be false
 - [x] create a chooseModalClass method
   - [x] if modal is active then it should return 'modal-box'
   - [x] if modal is not active then it should return 'hidden' 
 - [x] create a chooseModalClass method
   - [x] if modal is active then it should return 'overlay'
   - [x] if modal is not active then it should return 'hidden'
### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
