### ISSUE TITLE
User can send a challenge to other users

### ISSUE THREAD

**Issue by anthony-urbina** [AnthonyUrbina/final-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can send a challenge to other users.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Once the "War Multiplayer" modal appears, the user will be able to challenge other users by clicking on their faces. A new modal will appear after they initiate the challenge, confirming that the challenge has been sent. The user will be able to cancel the request if they choose. If they choose to cancel they will return to the home page. Else, they will remain idle until their opponent accepts or declines the challenge.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-11-07 at 11 41 33 AM](https://user-images.githubusercontent.com/109625982/200407939-a00061a5-261b-4f46-bb84-dec8979b229f.png)
![Screen Shot 2022-11-07 at 11 42 15 AM](https://user-images.githubusercontent.com/109625982/200407928-fe44c3d8-eb39-4070-9d9c-62db29ff1a8b.png)
![Screen Shot 2022-11-07 at 11 44 42 AM](https://user-images.githubusercontent.com/109625982/200407973-ac7ff786-633b-492d-b592-71c1adb27545.png)
![Screen Shot 2022-11-07 at 11 45 09 AM](https://user-images.githubusercontent.com/109625982/200407977-c134a9b7-41ba-44be-bf1f-2539e59c1df0.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] socket.on('invite-sent', opponentSocketId) to listen for invitation
  - [x] assign socket.id to const challengerSocketId
  - [x] create an array with opponentSocketId and challengerSocketId
  - [x] sort it, then join it with a - in between the two elements to create a unique roomId
  - [x] have the challenger join the roomId with socket.join(roomId)
  - [x] invite the opponent to join the room with socket.to(opponentSocketId).emit('invite-received', roomId)
- [x] socket.on('invite-canceled', opponentSocketId)
  - [x] the challenger should leave the custom room
  - [x] the challenger should .emit('invite-canceled') to their opponent 

### ⚡ Client Tasks

- [x] Update 'Lobby' React Element to include a challenger modal that matches the figma design
    - [x] add a 'isReceivingChallengeFrom' and 'isSendingChallengeTo' property to state
    - [x] both values should be null
- [x] in showOnlinePlayers method
  - [x] add data property to each img element, it should store the player's username
- [x] create getOpponentSocketId method
  - [x] it needs opponentUsername as a parameter
  - [x] it should loop through this.state.onlinePlayers object
  - [x] if onlinePlayers[key] equals opponentUsername
  - [x] then return that value's corresponding property (which is that user's socket.id)
- [x] in handleClick method
    - [x] when a player avatar or username is clicked
    - [x] retrieve it's data-username property value
    - [x] pass it as an argument to getOpponentSocketId()
    - [x] assign it's return value to const opponentSocketId
    - [x] use socket.emit('invite-sent', opponentSocketId) to invite that online player to a room
    - [x] once the invite is sent, use setState() to update 'isSendingChallengeTo' to opponentUsername
  - [x] when a challenger clicks 'Cancel' in the challengeModal
    - [x] use socket.emit('invite-canceled', opponentSocketId)
    - [x] use setState() to update 'isSendingChallengeTo' property to null
- [x] create a chooseChallengeModalTitle method
  - [x] if this.state.isSendingChallengeTo is truthy
  - [x] return 'Challenge Sent'
- [x] create a chooseChallengeModalText
  - [x] if this.state.isSendingChallengeTo is truthy
  - [x] return 'You have challenged playerUsername to a game. Waiting for their response...'
- [x] create a chooseChallengeModalButtons
  - [x] if this.state.isSendingChallengeTo is truthy
  - [x] return one button with textContent 'Cancel'
### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
