### ISSUE TITLE
User can receive a challenge from other users

### ISSUE THREAD

**Issue by anthony-urbina** [AnthonyUrbina/final-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can receive a challenge from other users

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user enters the app, their name and avatar will be viewable in the "War Multiplayer" modal. This will allow other users to send the user challenges as long as they are on the home page. A modal will appear to notify the user when they have a challenge. The user can either accept or decline this challenge. If they decline, they will return to the home page. Else, they will be entered into a lobby with the challenger.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-11-07 at 12 35 49 PM](https://user-images.githubusercontent.com/109625982/200410038-af2b808a-d433-42b4-9945-f0719bf6db89.png)
![Screen Shot 2022-11-07 at 12 33 28 PM](https://user-images.githubusercontent.com/109625982/200410037-1bf5e997-6bf5-40a4-bdfe-42435f5ef875.png)
![Screen Shot 2022-11-07 at 12 32 52 PM](https://user-images.githubusercontent.com/109625982/200409896-c1c089e1-d811-489e-8919-3734d8ef8023.png)
![Screen Shot 2022-11-07 at 12 32 41 PM](https://user-images.githubusercontent.com/109625982/200410180-f77d2994-0946-4fc9-a5f2-f45a2398a535.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to ...
- [x] on socket.on('invite-received', roomId) send the client roomId and challengerSocketId instead of just roomId
- [x] on socket.on('invite-accepted', inviteInfo)
  - [x] socket.join(inviteInfo.roomId)
  - [x] socket.to(roomId).emit('opponent-joined')
- [x] on socket.on('invite-declined', roomId)
  - [x] socket.to(roomId).emit('opponent-declined')
### ⚡ Client Tasks

- [x] Update 'Lobby' React Element to include a "challenge received" modal that matches the figma design
- [x] add opponentModalisActive property to state
- [x] add challengerModalisActive property to state
- [x] add roomId property to state
- [x] in componentDidMount()
  - [x] listen for socket.on("invite-received", inviteInfo)
    - [x] loop through this.state.onlinePlayers to find the challengerUsername of the corresponding challengerSocketId
    - [x] use setState() to updated
    - [x] isReceivingChallengeFrom property value to inviteInfo.opponentUsername
    - [x] roomId property value to inviteInfo.roomId
    - [x] onlinePlayerModalisActive value to boolean false
    - [x] opponentModalisActive property value to boolean true
  - [x] listen for socket.on('opponent-declined')
    - [x] use setState() to update
    - [x]  isSendingChallengeto property value to null
    - [x] challengerModalisActive property value to false
  - [x] listen for socket.on('opponent-joined')
    - [x] use setState() to update
    - [x] challengerModalisActive property value to false
  - [x] listen for socket.on('opponent-declined')
    - [x] use setState() to update
    - [x] opponentModalisActive property value to false
    - [x] isReceivingChallengeFrom property value to null
    - [x] roomId property value to null
- [x] in handleClick() method
  - [x] if the accept button is clicked
    - [x] this.socket.emit('invite-accepted', roomId)
  - [x] if the decline button is clicked
    - [x] this.socket.emit('invite-declined', roomId)
- [x] in chooseChallengeModalClass
  - [x] if user is being challenged
    - [x] className should be set to equal 'opponent-modal-box'
  - [x] else, it should be set equal to 'challenger-modal-box'
- [x] in chooseChallengeModalText() method
  - [x] if user is being challenged
    - [x] className should be set to equal 'opponent-modal-text'
  - [x] else, it should be set equal to 'challenger-modal-text'
- [x] in chooseChallengeModalButtons() method
  - [x] if user is being challenged
    - [x] it should return two buttons. 'accept' and 'decline'
  - [x] else, it should return one button. 'cancel'

### 🧑‍⚕️ Clean Up Tasks

 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
