### ISSUE TITLE
User can enter a lobby

### ISSUE THREAD

**Issue by anthony-urbina** [AnthonyUrbina/final-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can enter a lobby.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

One a challenge request is sent by one user and accepted by another, both users will be placed in the lobby where their match will occur.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-11-07 at 11 42 15 AM](https://user-images.githubusercontent.com/109625982/200421276-c0a6595f-7773-4e9d-bf7e-72308722ba93.png)
![Screen Shot 2022-11-07 at 11 42 34 AM](https://user-images.githubusercontent.com/109625982/200421292-0a36229c-76f1-44aa-844a-ab3a4b2b86ed.png)
![Screen Shot 2022-11-07 at 12 33 28 PM](https://user-images.githubusercontent.com/109625982/200421391-7e5d4d5e-565a-4050-bbfb-29d08ecf9094.png)
![Screen Shot 2022-11-07 at 12 35 49 PM](https://user-images.githubusercontent.com/109625982/200421394-820d1ac7-5bd8-423f-af29-4e5dc1969905.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` 
- [x] games table should have a autoincrementing gameId
- [x] usernames must be unique
### ☁️ Server Tasks

- [x] Update `server/index.js` to use usernames to create roomId instead of socketIds
- [x] socket.on('invite-sent'), make updates
  - [x] use opponentSocketId to get the opponentUsername
  - [x] use challengerSocketId to get the challengerUsername
  - [x] use both usernames to create a roomId
  - [x] make sure to join the room
  - [x] inviteInfo object should hold roomId and challengerUsername
  - [x] socket.to(opponentSocketId).emit('invite-received', inviteInfo)
- [x] socket.on('invite-canceled'), make updates
  - [x] create a roomId with opponentUsername and challengerUsername
- [x] create a GET route at 'api/games/retrieve
  - [x] query the database
  - [x] select 'username' columns for the 'challenger' or 'opponent' columns who's values are equal to the 
          userId making the request
  - [x] respond to the client with a 200 OK response, include the entire row in the response
  - [x] catch all errors
- [x] if the connecting socket has a jwt
- [x] decode it using jwtDecode()
- [x]  assign the username from the payload to the nickname property of the socket making the connection
- [x] assign the userId from the payload to the userId property of the socket making the connection
### ⚡ Client Tasks

- [x] Create a 'CompetitionPage' component to match from figma design
- [x] on hashchange re-route them over to the CompetitionPage
- [x] in CompetitionPage Component
- [x] componentDidMount()
 - [x] make a fetch request for the row of the games table the current client is in
   - [x] then
   - [x] parse json response
   - [x] then
   - [x] parse the window hashroute and assign the return's path property to const roomId
   - [x] map through results (array with two player objects containing usernames), and return an array of 
           usernames
   - [x] if client has a token
   - [x] grab it from local storage
   - [x] open a new socket connection
   - [x] pass token via auth option
   - [x] pass roomId via queries option
- [x] create a renderPlayer2() method
   - [x] parse the window hashroute and assign the return's path property to const roomId
   - [x] split the string by the '-', then loop through the returned array
   - [x] return the element that does not equal this.props.token.username (current client)
   - [x] use setState() to update the opponent property with the returned value from the loop
- [x] Update Lobby component (using usernames for roomId instead of socketIds)
- [x] componentDidMount()
  - [x] remove for loop that uses inviteInfo.challengerSocketId to retrieve challengerUsername from 
            this.state.onlinePlayers
  - [x] when establishing lobby connection, send jwt from localstorage instead of user payload
  - [x] use inviteInfo.challengerUsername to update state's isReceivingChallengeFrom property
  - [x] in handleClick() method
  - [x] if user clicks the 'accept-invite button'
    - [x] make a post request to '/api/games/create'
    - [x] create a new row in the 'games' table with challengerUsername and opponentUsername
    - [x] window.location.hash = 'this.state.roomId'
### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
