### ISSUE TITLE
User can flip a card

### ISSUE THREAD

**Issue by anthony-urbina** [AnthonyUrbina/final-project#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can flip a card.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will have a deck of cards. In order to place a card on the table, the user will click on their deck of cards. Once they do so, they will see their card, face-up, center table.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-11-07 at 2 00 03 PM](https://user-images.githubusercontent.com/109625982/200427772-3e9d7f2c-2b89-483e-80d7-118a37f44dc1.png)
![Screen Shot 2022-11-07 at 2 00 13 PM](https://user-images.githubusercontent.com/109625982/200427775-cba2585c-47e8-4010-b2f8-075933f86e3b.png)
![Screen Shot 2022-11-07 at 2 02 12 PM](https://user-images.githubusercontent.com/109625982/200427805-0aaee1c3-8d7b-41e7-a15e-5a42e139e7ae.png)
![Screen Shot 2022-11-07 at 2 02 29 PM](https://user-images.githubusercontent.com/109625982/200427807-91a3871e-db99-474d-ab78-517b42f7b0ea.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to ...
- [x] create a players array of objects, name, type, and hand properties
- [x] create an array with all card ranks (besides joker)
- [x] create an array with all card suits (spades, diamonds, etc)
- [x] create an all array with all 52 card images
- [x] create a createDeck() method
  - [x] create deck array
  - [x] create a card object
  - [x] loop through the ranks array
  - [x] loop through the suits array
  - [x] create a card for every rank/suit combination
  - [x] push the card to the deck array
  - [x] return the deck array
- [x] shuffle the cards using lodash shuffle function
- [x] split the deck in half and assign a half to challenger and opponent
- [x] on socket.on('invite-accepted')
  - [x] pass the players array to both clients via socket.to(roomId).emit('decks-created', players)
- [x] create a patch route at api '/api/games/:gameId'
  - [x] grab req params and req body
  - [x] query the database
    - [x] update "state"
    - [x] in the "games" table 
    - [x] where gameId equals that of the current session
    - [x] return the updated row
    - [x] then
      - [x] throw new client error if no game with that gameId was found
      - [x] else, respond with a 204 No Content status and the row that was updated
    - [x] catch all errors
- [x] create a get route at '/api/games/retrieve/:gameId'
  - [x] grab req params
  - [x] make a db query to return the state of the given gameId
  - [x] return the row
  - [x] then
      - [x] throw new client error if no game with that gameId was found
      - [x] else, respond to the client with a 200 request and the row that was returned
  - [x] catch all errors
### ⚡ Client Tasks

- [x] Update component to ...
- [x] add clientCardShowing and opponentCardShowing property to state
- [x] add clientDeck and opponentDeck property to state
- [x] add gameId property to state
- [x] in competitionRoom component
- [x] in componentDidMount
  - [x] make get request to 'api/games/retrieve/:userId'
  - [x] get the state of the current game
  - [x] use setState to update current state
- [x] create a flipCard() method
  - [x] it should remove the flipped card's object from a copy the client's deck array
  - [x] save all new data to a copy of the state
  - [x] it should send a fetch request (patch) to '/api/games/:gameId
    - [x] method: patch
    - [x] body: stringified version of the copy of state
    - [x] content type: 'application/json'
  - [x] it should use setState to update the clientCardShowing property value and the clientDeck property value
### 🧑‍⚕️ Clean Up Tasks

 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
