### ISSUE TITLE
User can see opponent's card flip in real time

### ISSUE THREAD

**Issue by anthony-urbina** [AnthonyUrbina/final-project#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see opponent's card flip in real time.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When a match starts, both users in the game will be able to see each-other's card flips happen in real time, just as if they were playing in person.
 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-11-07 at 2 00 13 PM](https://user-images.githubusercontent.com/109625982/200428125-79a54970-3782-4d42-8bf6-46ff55b4d165.png)
![Screen Shot 2022-11-07 at 2 01 01 PM](https://user-images.githubusercontent.com/109625982/200428129-34ef3247-32ec-4714-81f1-963dc496439f.png)
![Screen Shot 2022-11-07 at 2 02 43 PM](https://user-images.githubusercontent.com/109625982/200428156-d7df272f-942f-4b88-a4f2-115121f37d1c.png)
![Screen Shot 2022-11-07 at 2 02 54 PM](https://user-images.githubusercontent.com/109625982/200428157-fed09181-eb6e-4cda-bdde-73f81d873b0b.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Create a component to ...
- [x] Update component to ...
- [x] create showClientCard() method
  - [x] check if opponentCard is showing
    - [x] if client has not placed a card down yet add 'flipped-first' to the className of the img that will be made
    - [x] return an img element with className 'flipped-card opponent-card'
- [x] update createCard() method and change name to showOpponentCard()
  - [x] check if clientCard is showing
    - [x] if opponent has not placed a card down yet add 'flipped-first' to the className of the img that will be made
### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
